services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: varchat_postgres
    restart: always
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: varchat_db
    volumes: 
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-varchat_db}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - varchat_network

  redis:
    image: redis:8.4.0-alpine
    container_name: varchat_redis
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    ports: 
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - varchat_network

volumes:
  postgres_data: 
  redis_data:

networks: 
  varchat_network:
    driver: bridge